# .github/workflows/manual-deploy.yml
# Tên của workflow, hiển thị trên tab "Actions"
name: Manual Deploy to Staging/Production

# Trigger workflow này một cách thủ công từ giao diện GitHub Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        type: choice
        required: true
        options:
          - STG # Môi trường Staging
          - PROD # Môi trường Production
      tag_to_deploy:
        description: "Specify the tag to deploy (e.g., v1.2.3 or v1.2.3-canary.1). Leave empty to deploy the LATEST tag for the selected environment."
        type: string
        required: false # Không bắt buộc phải nhập
        default: "" # Giá trị mặc định là trống

jobs:
  # Job đầu tiên: Xác định tag nào sẽ được deploy
  get_tag_or_use_input:
    runs-on: ubuntu-latest
    outputs:
      final_release_tag: ${{ steps.determine_tag.outputs.tag }} # Output tag đã xác định
      is_prerelease_flag: ${{ steps.determine_tag.outputs.is_prerelease }} # Output cờ pre-release
    steps:
      - name: Determine Tag to Deploy
        id: determine_tag # Gán ID để truy cập output của bước này
        uses: actions/github-script@v7 # Sử dụng github-script để tương tác với GitHub API
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const environment = "${{ github.event.inputs.environment }}";
            let tagToDeploy = "${{ github.event.inputs.tag_to_deploy }}";
            let isPrerelease = false; // Mặc định là false

            if (tagToDeploy) {
              // Nếu người dùng đã nhập tag, sử dụng tag đó
              console.log(`User specified tag: ${tagToDeploy}`);
              // Cố gắng xác định is_prerelease từ tên tag (thường các pre-release tag có hậu tố như -canary, -beta, -alpha)
              isPrerelease = tagToDeploy.includes('canary') || tagToDeploy.includes('beta') || tagToDeploy.includes('alpha');
            } else {
              // Nếu người dùng không nhập, tìm tag mới nhất thông qua GitHub API Releases
              console.log(`No tag specified. Finding latest release for ${environment} environment.`);
              const { data: releases } = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 10, // Lấy 10 release gần nhất để tìm kiếm
              });

              let latestFoundRelease = null;
              if (environment === 'PROD') {
                // Tìm bản release mới nhất KHÔNG phải là pre-release (production)
                latestFoundRelease = releases.find(release => !release.prerelease);
                isPrerelease = false;
              } else { // environment === 'STG'
                # Tìm bản release mới nhất LÀ pre-release (staging)
                latestFoundRelease = releases.find(release => release.prerelease);
                isPrerelease = true;
              }

              if (latestFoundRelease) {
                tagToDeploy = latestFoundRelease.tag_name;
                console.log(`Found latest tag for ${environment}: ${tagToDeploy}`);
              } else {
                console.log(`No suitable release found for ${environment}. Aborting.`);
                // Nếu không tìm thấy tag, đánh dấu bước này là thất bại
                core.setFailed(`No suitable release found for ${environment} environment.`);
                return; // Ngừng script
              }
            }
            # Thiết lập output của bước này để job tiếp theo có thể truy cập
            core.setOutput('tag', tagToDeploy);
            core.setOutput('is_prerelease', isPrerelease.toString()); # Chuyển boolean thành chuỗi 'true'/'false'
