name: Get Tag For Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build for (e.g., STG or PROD)"
        type: choice
        required: true
        options:
          - STG
          - PROD
      tag_to_deploy:
        description: "Specify the tag to deploy (e.g., v1.2.3). Leave empty to deploy the LATEST tag for the selected environment."
        type: string
        required: false
        default: ""

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.final_tag.outputs.tag }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git bot user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if tag is not provided
        run: |
          if [ -z "${{ github.event.inputs.tag_to_deploy }}" ]; then
            echo "❌ No tag specified. The 'tag_to_deploy' input is required."
            exit 1
          fi

      - name: Check if tag exists
        id: check_tag
        run: |
          TAG="${{ github.event.inputs.tag_to_deploy }}"
          echo "🔍 Checking if tag '$TAG' exists in the repository."
          if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "✅ Tag '$TAG' exists."
          else
            echo "❌ Tag '$TAG' not found in the repository."
            exit 1
          fi
