name: GitHub Release + Push CHANGELOG

on:
  push:
    tags:
      - "v*"
      - "staging-v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch from tag
        id: branch
        run: |
          if [[ "${GITHUB_REF_NAME}" == staging-v* ]]; then
            echo "branch=dev" >> $GITHUB_OUTPUT
          else
            echo "branch=main" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull target branch
        run: |
          git fetch origin ${{ steps.branch.outputs.branch }}
          git switch ${{ steps.branch.outputs.branch }}

      - name: Commit updated CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -m "docs(changelog): update for ${{ github.ref_name }}" || echo "No changes"
          git push origin ${{ steps.branch.outputs.branch }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
