name: Semantic Release

on:
  push:
    branches:
      - dev
      - main
      - staging

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node & bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4

      - name: Install deps
        run: bun install

      - name: Run semantic release for Main branch
        if: github.ref_name == 'main'
        run: bunx semantic-release --config .releaserc.main.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run semantic release for Staging branch
        if: github.ref_name == 'staging'
        run: bunx semantic-release --config .releaserc.staging.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run semantic release for Dev branch
        if: github.ref_name == 'dev'
        run: bunx semantic-release --config .releaserc.dev.js
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
