name: Semantic Release PR

on:
  push:
    branches:
      - dev # Hoặc nhánh bạn muốn chạy release PR

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4

      - name: Install dependencies
        run: bun install

      - name: Install JQ
        run: sudo apt-get update && sudo apt-get install -y jq
        # This ensures jq is available.

      - name: Configure Git for Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Git user configured for automated actions."

      - name: Run semantic-release (get release info)
        id: semantic_release_run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Verifying npx availability..."
          which npx || { echo "npx not found! Exiting."; exit 1; }
          echo "npx is located at: $(which npx)"

          echo "Verifying semantic-release package..."
          npx --version || { echo "npx failed to run. Exiting."; exit 1; }
          npx semantic-release --help > /dev/null || { echo "semantic-release not callable via npx! Exiting."; exit 1; }
          echo "semantic-release is callable via npx."

          echo "Verifying jq availability..."
          which jq || { echo "jq not found! Exiting."; exit 1; }
          echo "jq is located at: $(which jq)"

          echo "Running semantic-release..."
          npx semantic-release --debug 2>&1 | tee semantic_release_raw_output.txt

          # Capture the raw output as an artifact for debugging
          echo "Uploading semantic_release_raw_output.txt as an artifact..."
          echo "::set-output name=raw_output_path::semantic_release_raw_output.txt"

          # Attempt to extract the last JSON object from the raw output.
          # semantic-release outputs the nextRelease JSON object right at the end upon success.
          # This regex looks for lines that start with '{' and end with '}'
          RELEASE_OUTPUT=$(cat semantic_release_raw_output.txt | grep -E '^\s*\{.*\}\s*$' | tail -n 1)

          if [ -n "$RELEASE_OUTPUT" ]; then
            echo "Found semantic-release JSON output:"
            echo "$RELEASE_OUTPUT"
            echo "release_output_json<<EOF" >> "$GITHUB_OUTPUT"
            echo "$RELEASE_OUTPUT" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            echo "No semantic-release JSON output found (no new release determined or parsing failed)."
            echo "release_output_json={}" >> "$GITHUB_OUTPUT" # Ensure output variable is always set
          fi

          echo "--- Content of CHANGELOG.md after semantic-release ---"
          cat CHANGELOG.md || echo "CHANGELOG.md not found or empty."
          echo "--- Content of package.json after semantic-release ---"
          cat package.json || echo "package.json not found or empty."

      - name: Upload semantic-release raw output
        uses: actions/upload-artifact@v4
        with:
          name: semantic-release-raw-output
          path: semantic_release_raw_output.txt

      - name: Parse semantic-release output for new version and release notes
        id: get_release_info
        run: |
          NEW_VERSION=""
          RELEASE_NOTES=""

          RELEASE_JSON="${{ steps.semantic_release_run.outputs.release_output_json }}"

          # Only attempt to parse if the JSON is not empty and is valid
          if [ -n "$RELEASE_JSON" ] && echo "$RELEASE_JSON" | jq -e '.' &>/dev/null; then
            if echo "$RELEASE_JSON" | jq -e '.nextRelease.version' &>/dev/null; then
              NEW_VERSION=$(echo "$RELEASE_JSON" | jq -r '.nextRelease.version')
            fi
            if echo "$RELEASE_JSON" | jq -e '.nextRelease.notes' &>/dev/null; then
              RELEASE_NOTES=$(echo "$RELEASE_JSON" | jq -r '.nextRelease.notes')
            fi
          fi

          if [ -z "$NEW_VERSION" ]; then
            echo "No new version determined by semantic-release. Skipping PR creation."
            echo "new_version=none" >> "$GITHUB_OUTPUT"
          else
            echo "New version determined: $NEW_VERSION"
            echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
            mkdir -p ./.github/release-assets
            echo "$RELEASE_NOTES" > ./.github/release-assets/release_notes.md
            echo "release_notes_file=./.github/release-assets/release_notes.md" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip if no version bump
        if: steps.get_release_info.outputs.new_version == 'none'
        run: |
          echo "No version bump detected by semantic-release. Workflow will stop here."
          exit 0

      - name: Read Release Notes for PR Body
        id: read_release_notes
        run: |
          RELEASE_NOTES_FILE="${{ steps.get_release_info.outputs.release_notes_file }}"
          if [ -f "$RELEASE_NOTES_FILE" ]; then
            RELEASE_NOTES_CONTENT=$(cat "$RELEASE_NOTES_FILE")
            echo "release_notes_pr_body<<EOF" >> "$GITHUB_OUTPUT"
            echo "$RELEASE_NOTES_CONTENT" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            echo "No release notes file found, setting empty notes."
            echo "release_notes_pr_body=No detailed release notes available." >> "$GITHUB_OUTPUT"
          fi

      - name: Update package.json version
        run: |
          NEW_VERSION="${{ steps.get_release_info.outputs.new_version }}"
          echo "Updating package.json to version $NEW_VERSION"
          jq ".version = \"$NEW_VERSION\"" package.json > package.json.tmp && mv package.json.tmp package.json
          echo "package.json updated."
          echo "--- Content of package.json after update ---"
          cat package.json

      - name: Create Release Branch
        id: create_branch
        run: |
          NEW_VERSION="${{ steps.get_release_info.outputs.new_version }}"
          BRANCH_NAME="release/v$NEW_VERSION"
          echo "Creating new branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

      - name: Commit version and changelog changes to new branch
        run: |
          NEW_VERSION="${{ steps.get_release_info.outputs.new_version }}"
          git add CHANGELOG.md package.json
          if ! git diff --cached --exit-code; then
            git commit -m "chore(release): prepare for v$NEW_VERSION release PR [skip ci]"
            echo "Committed version and changelog changes to branch."
          else
            echo "No changes in CHANGELOG.md or package.json to commit."
          fi

      - name: Push Release Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.create_branch.outputs.branch_name }}"
          git push origin "$BRANCH_NAME"
          echo "Pushed branch: $BRANCH_NAME to remote."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): prepare for v${{ steps.get_release_info.outputs.new_version }} release PR"
          title: "Release v${{ steps.get_release_info.outputs.new_version }}"
          body: |
            ## Release v${{ steps.get_release_info.outputs.new_version }}

            This Pull Request includes the following automated updates for the upcoming release:

            - **Version Bump**: Updated `package.json` to `v${{ steps.get_release_info.outputs.new_version }}`.
            - **Changelog Update**: Added a new entry to `CHANGELOG.md` with release notes generated from recent commits.

            ---
            ### Release Notes:
            ${{ steps.read_release_notes.outputs.release_notes_pr_body }}

            ---
            Please review these changes, especially the changelog content, before merging this PR. Merging this PR will finalize the version update and integrate the changelog into the `main` branch.
          branch: ${{ steps.create_branch.outputs.branch_name }}
          base: dev
          labels: |
            release
            automated
          draft: false

      - name: Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_release_info.outputs.new_version }}
          release_name: Release v${{ steps.get_release_info.outputs.new_version }}
          body: |
            ${{ steps.read_release_notes.outputs.release_notes_pr_body }}

            Please refer to the [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/v${{ steps.get_release_info.outputs.new_version }}/CHANGELOG.md) for full details on this release.
          draft: false
          prerelease: contains(github.ref, 'dev')
