name: Semantic Release PR

on:
  push:
    branches:
      - dev # Nhánh bạn muốn chạy release PR

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node & Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4

      - name: Install dependencies
        run: bun install

      - name: Configure Git for Actions
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Git user configured for automated actions."

      # Cập nhật bước này để capture output của semantic-release
      # và xử lý nó cẩn thận hơn.
      - name: Run semantic-release (get release info)
        id: semantic_release_run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Chạy semantic-release và kiểm tra xem có nextRelease không.
          # Output được chuyển hướng để chỉ lấy phần JSON.
          # Nếu không có nextRelease, output sẽ rỗng hoặc không có .nextRelease.
          RELEASE_OUTPUT=$(npx semantic-release --debug | grep -A 100 "Release success" | tail -n +2 | jq .)

          # Lưu output đã được xử lý vào một biến output của step
          echo "release_output_json<<EOF" >> "$GITHUB_OUTPUT"
          echo "$RELEASE_OUTPUT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

          # Để kiểm tra, in ra nội dung của file CHANGELOG.md và package.json
          echo "--- Content of CHANGELOG.md after semantic-release ---"
          cat CHANGELOG.md || echo "CHANGELOG.md not found or empty."
          echo "--- Content of package.json after semantic-release ---"
          cat package.json || echo "package.json not found or empty."

      - name: Parse semantic-release output for new version and release notes
        id: get_release_info
        run: |
          NEW_VERSION=""
          RELEASE_NOTES=""

          # Lấy nội dung JSON từ output của bước trước
          RELEASE_JSON="${{ steps.semantic_release_run.outputs.release_output_json }}"

          # Kiểm tra nếu JSON không rỗng và có thể parse được
          if [ -n "$RELEASE_JSON" ] && echo "$RELEASE_JSON" | jq -e '.' &>/dev/null; then
            # Lấy nextRelease.version
            if echo "$RELEASE_JSON" | jq -e '.nextRelease.version' &>/dev/null; then
              NEW_VERSION=$(echo "$RELEASE_JSON" | jq -r '.nextRelease.version')
            fi
            
            # Lấy release notes (nếu có)
            if echo "$RELEASE_JSON" | jq -e '.nextRelease.notes' &>/dev/null; then
              RELEASE_NOTES=$(echo "$RELEASE_JSON" | jq -r '.nextRelease.notes')
            fi
          fi

          if [ -z "$NEW_VERSION" ]; then
            echo "No new version determined by semantic-release. Skipping PR creation."
            echo "new_version=none" >> "$GITHUB_OUTPUT"
          else
            echo "New version determined: $NEW_VERSION"
            echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
            # Lưu release notes vào file để sử dụng trong PR body
            # Đảm bảo thư mục tồn tại nếu bạn muốn lưu vào subfolder
            mkdir -p ./.github/release-assets
            echo "$RELEASE_NOTES" > ./.github/release-assets/release_notes.md
            echo "release_notes_file=./.github/release-assets/release_notes.md" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip if no version bump
        if: steps.get_release_info.outputs.new_version == 'none'
        run: |
          echo "No version bump detected by semantic-release. Workflow will stop here."
          exit 0

      - name: Read Release Notes for PR Body
        id: read_release_notes
        run: |
          RELEASE_NOTES_FILE="${{ steps.get_release_info.outputs.release_notes_file }}"
          if [ -f "$RELEASE_NOTES_FILE" ]; then
            RELEASE_NOTES_CONTENT=$(cat "$RELEASE_NOTES_FILE")
            echo "release_notes_pr_body<<EOF" >> "$GITHUB_OUTPUT"
            echo "$RELEASE_NOTES_CONTENT" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          else
            echo "No release notes file found, setting empty notes."
            echo "release_notes_pr_body=No detailed release notes available." >> "$GITHUB_OUTPUT"
          fi

      - name: Create Release Branch
        id: create_branch
        run: |
          NEW_VERSION="${{ steps.get_release_info.outputs.new_version }}"
          BRANCH_NAME="release/v$NEW_VERSION"
          echo "Creating new branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

      - name: Commit version and changelog changes to new branch
        run: |
          NEW_VERSION="${{ steps.get_release_info.outputs.new_version }}"
          # Thêm CHANGELOG.md và package.json.
          # Đảm bảo semantic-release đã thực sự thay đổi chúng.
          git add CHANGELOG.md package.json
          # Sử dụng git diff --cached --exit-code để kiểm tra xem có thay đổi nào để commit không
          # Nếu không có thay đổi, lệnh sẽ exit với code 0, nếu có sẽ là 1.
          if ! git diff --cached --exit-code; then
            git commit -m "chore(release): prepare for v$NEW_VERSION release PR [skip ci]"
            echo "Committed version and changelog changes to branch."
          else
            echo "No changes in CHANGELOG.md or package.json to commit."
          fi

      - name: Push Release Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${{ steps.create_branch.outputs.branch_name }}"
          # Chỉ push nếu có commit mới trên nhánh này
          git push origin "$BRANCH_NAME" --force-with-lease || true # Dùng --force-with-lease nếu cần, nhưng cẩn thận.
          # Tốt nhất nên kiểm tra remote trước:
          # if git ls-remote --exit-code origin "$BRANCH_NAME"; then
          #   echo "Branch $BRANCH_NAME already exists on remote. Skipping push."
          # else
          #   git push origin "$BRANCH_NAME"
          # fi
          echo "Pushed branch: $BRANCH_NAME to remote (if changes were committed)."

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): prepare for v${{ steps.get_release_info.outputs.new_version }} release PR"
          title: "Release v${{ steps.get_release_info.outputs.new_version }}"
          body: |
            ## Release v${{ steps.get_release_info.outputs.new_version }}

            This Pull Request includes the following automated updates for the upcoming release:

            - **Version Bump**: Updated `package.json` to `v${{ steps.get_release_info.outputs.new_version }}`.
            - **Changelog Update**: Added a new entry to `CHANGELOG.md` with release notes generated from recent commits.

            ---
            ### Release Notes:
            ${{ steps.read_release_notes.outputs.release_notes_pr_body }}

            ---
            Please review these changes, especially the changelog content, before merging this PR. Merging this PR will finalize the version update and integrate the changelog into the `main` branch.
          branch: ${{ steps.create_branch.outputs.branch_name }}
          base: dev # Nhánh đích của PR (nhánh được bảo vệ)
          labels: |
            release
            automated
          draft: false

      - name: Create GitHub Release
        if: success() # Chỉ tạo GitHub Release nếu mọi bước trước đó thành công
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_release_info.outputs.new_version }}
          release_name: Release v${{ steps.get_release_info.outputs.new_version }}
          body: |
            ${{ steps.read_release_notes.outputs.release_notes_pr_body }}

            Please refer to the [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/v${{ steps.get_release_info.outputs.new_version }}/CHANGELOG.md) for full details on this release.
          draft: false
          prerelease: contains(github.ref, 'dev')
