name: Semantic Release with PR

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Quan trọng để semantic-release có đầy đủ lịch sử git

      - name: Setup Node & bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4 # Đảm bảo phiên bản bun bạn muốn dùng

      - name: Install dependencies
        run: bun install

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run semantic-release
        id: semantic
        # Chạy semantic-release. Bây giờ plugin @semantic-release/git sẽ không push.
        # Output sẽ được xuất ra stdout.
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Sử dụng GH_TOKEN của bạn

      - name: Create Pull Request for Release
        # Điều kiện sẽ hoạt động chính xác vì semantic-release đã chạy thành công
        # và output new_release_published sẽ đúng.
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }} # Token có quyền tạo PR
          commit-message: "chore(release): prepare for new release" # Tiêu đề commit cho PR
          title: "chore(release): New Release Candidate for ${{ github.ref_name }}" # Tiêu đề của PR
          body: |
            This Pull Request contains the automated release changes from `semantic-release`.

            **Release Notes:**
            ${{ steps.semantic.outputs.release_notes }}
          branch: "release/candidate-${{ github.ref_name }}" # Nhánh tạm thời sẽ tạo ra
          base: ${{ github.ref_name }} # Nhánh đích mà PR sẽ merge vào
          labels: "release, automated-pr" # Gán nhãn cho PR
          # reviewers: your_github_username # (Tùy chọn) Thêm người đánh giá nếu cần
