name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Release Please GitHub Action
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: foodblog_fe_v2
