name: Semantic Release with PR

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Quan trọng để semantic-release có đầy đủ lịch sử git

      - name: Setup Node & bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.4 # Đảm bảo phiên bản bun bạn muốn dùng

      - name: Install dependencies
        run: bun install

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run semantic-release and capture output
        id: semantic
        continue-on-error: true # Cho phép bước này không làm workflow dừng lại khi gặp lỗi
        run: |
          # Chạy semantic-release và ghi toàn bộ output (stdout và stderr) vào một biến
          OUTPUT=$(bunx semantic-release --debug 2>&1 || true)
          echo "$OUTPUT"

          # KIỂM TRA XEM CÓ BẢN RELEASE MỚI ĐƯỢC XÁC ĐỊNH KHÔNG
          # Tìm dòng "The next release version is X.Y.Z"
          # Nếu dòng này tồn tại, nghĩa là semantic-release đã quyết định tạo một bản release
          if echo "$OUTPUT" | grep -q "\[semantic-release\] › ℹ  The next release version is"; then
            NEW_RELEASE_PUBLISHED="true"
            echo "Semantic-release determined a new release is needed."
          else
            NEW_RELEASE_PUBLISHED="false"
            echo "Semantic-release did not determine a new release is needed."
          fi

          # PHÂN TÍCH RELEASE NOTES
          # Tìm phần release notes giữa "generateNotes" và "prepare" hoặc "prepare" và "Failed step"
          # Lấy các dòng nằm giữa "Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator""
          # và "Start step "prepare" of plugin "@semantic-release/changelog""
          # hoặc "Start step "prepare" of plugin "@semantic-release/git""
          # Đoạn này cần phải rất cẩn thận để bắt đúng phần nội dung release notes.
          RELEASE_NOTES=$(echo "$OUTPUT" | \
            sed -n '/Completed step "generateNotes" of plugin "@semantic-release\/release-notes-generator"/,/Start step "prepare" of plugin "@semantic-release\/changelog"/p' | \
            head -n -1 | tail -n +2 | \
            sed '/^\[semantic-release\]/d' | sed '/^$/d' | tr -d '\r' || echo "No release notes generated.")

          # Nếu RELEASE_NOTES trống rỗng hoặc chỉ chứa khoảng trắng, đặt lại thông báo
          if [[ -z "${RELEASE_NOTES// }" ]]; then
            RELEASE_NOTES="No release notes available from semantic-release output."
          fi

          # Đặt output cho step này
          echo "new_release_published=$NEW_RELEASE_PUBLISHED" >> $GITHUB_OUTPUT
          echo "release_notes<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Đảm bảo biến này được truyền vào

      - name: Debug Semantic Release Output
        run: |
          echo "new_release_published: ${{ steps.semantic.outputs.new_release_published }}"
          echo "release_notes:"
          echo "${{ steps.semantic.outputs.release_notes }}"

      - name: Create Pull Request for Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }} # Token có quyền tạo PR
          commit-message: "chore(release): prepare for new release" # Tiêu đề commit cho PR
          title: "chore(release): New Release Candidate for ${{ github.ref_name }}" # Tiêu đề của PR
          body: |
            This Pull Request contains the automated release changes from `semantic-release`.

            **Release Notes:**
            ${{ steps.semantic.outputs.release_notes }}
          branch: "release/candidate-${{ github.ref_name }}" # Nhánh tạm thời sẽ tạo ra
          base: ${{ github.ref_name }} # Nhánh đích mà PR sẽ merge vào
          labels: "release, automated-pr" # Gán nhãn cho PR
          # reviewers: your_github_username # (Tùy chọn) Thêm người đánh giá nếu cần
