# .github/workflows/trigger-get-tag.yml
name: Manually Trigger Get Tag For Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build for (e.g., STG or PROD)"
        type: choice
        required: true
        options:
          - STG
          - PROD
      tag_to_deploy:
        description: "Specify the tag to deploy (e.g., v1.2.3). Leave empty to deploy the LATEST tag for the selected environment."
        type: string
        required: false
        default: ""

jobs:
  dispatch_get_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository dispatch event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: "run-get-tag-for-deploy" # This is the custom event name
          client-payload: |
            {
              "environment": "${{ github.event.inputs.environment }}",
              "tag_to_deploy": "${{ github.event.inputs.tag_to_deploy }}"
            }
