name: Update Changelog on Merge

on:
  push:
    branches:
      - dev
      - main # Đảm bảo nhánh bạn muốn theo dõi

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Quan trọng để lấy toàn bộ lịch sử commit

      - name: Run Changelog Generation Script
        run: |
          chmod +x ./scripts/generate_changelog.sh # Cấp quyền thực thi cho script
          ./scripts/generate_changelog.sh
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }} # Truyền tên nhánh vào script
